version: "3.6"

x-build-args: &build_args
  INSTALL_PYTHON_VERSION: "3.10"
  INSTALL_NODE_VERSION: "14"

x-default-volumes: &default_volumes
  volumes:
    - ./:/app
    - node-modules:/app/node_modules

services:
  database:
    image: 'postgres:14'
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./dev.db/:/var/lib/postgresql/data/

  flask-dev:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    image: "cfb_survivor_pool-development"
    depends_on:
      - database
    ports:
      - "8080:5000"
      - "2992:2992"
    <<: *default_volumes

  flask-prod:
    build:
      context: .
      target: production
      args:
        <<: *build_args
    image: "cfb_survivor_pool-production"
    depends_on:
      - database
    ports:
      - "8080:5000"
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
      LOG_LEVEL: info
      GUNICORN_WORKERS: 4
    <<: *default_volumes

  manage:
    build:
      context: .
      target: development
      args:
        <<: *build_args
    entrypoint: pipenv run flask
    environment:
      FLASK_ENV: production
      FLASK_DEBUG: 0
    image: "cfb_survivor_pool-manage"
    stdin_open: true
    tty: true
    <<: *default_volumes

volumes:
  node-modules:
