"""empty message

Revision ID: 0256c48d62dd
Revises: 0ab9afc7efeb
Create Date: 2022-08-08 02:07:19.765919

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0256c48d62dd'
down_revision = '0ab9afc7efeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Integer(), nullable=False),
    sa.Column('game', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.CheckConstraint('created < game.start_date', name='game_is_in_future'),
    sa.CheckConstraint('game.away_team = team OR game.home_team = team', name='team_matches'),
    sa.ForeignKeyConstraint(['game'], ['game.id'], ),
    sa.ForeignKeyConstraint(['team'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick')
    # ### end Alembic commands ###
