"""empty message

Revision ID: 0ab9afc7efeb
Revises: bf002a787846
Create Date: 2022-08-08 01:40:08.749937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ab9afc7efeb'
down_revision = 'bf002a787846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('saturday', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'saturday')
    # ### end Alembic commands ###
