"""empty message

Revision ID: 0d06507a4d4f
Revises: ca6d66718c3a
Create Date: 2022-08-14 04:29:26.526207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d06507a4d4f'
down_revision = 'ca6d66718c3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('conference', sa.String(length=80), nullable=False))
    op.add_column('entry', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'year')
    op.drop_column('entry', 'conference')
    # ### end Alembic commands ###
