"""empty message

Revision ID: 110f82c9a438
Revises: 5823a0b3fedd
Create Date: 2022-08-08 00:09:26.370214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '110f82c9a438'
down_revision = '5823a0b3fedd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'game', 'team', ['away_id'], ['id'])
    op.create_foreign_key(None, 'game', 'team', ['home_id'], ['id'])
    op.drop_column('game', 'away_team')
    op.drop_column('game', 'home_team')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('home_team', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('game', sa.Column('away_team', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    # ### end Alembic commands ###
