"""empty message

Revision ID: 1ad81b57b222
Revises: 2f32a5de1734
Create Date: 2022-08-07 03:15:34.471547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad81b57b222'
down_revision = '2f32a5de1734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('color', sa.String(length=10), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('team', 'color')
    # ### end Alembic commands ###
