"""empty message

Revision ID: 235015bb98b4
Revises: ff84f2f9c0e1
Create Date: 2022-08-08 03:51:24.112790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235015bb98b4'
down_revision = 'ff84f2f9c0e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('created', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'created')
    # ### end Alembic commands ###
