"""empty message

Revision ID: 2f32a5de1734
Revises: 2aa8aeb52d69
Create Date: 2022-08-07 02:46:12.386427

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f32a5de1734'
down_revision = '2aa8aeb52d69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('away_id', sa.Integer(), nullable=False),
    sa.Column('home_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('alt_color', sa.String(length=10), nullable=True),
    sa.Column('classification', sa.String(length=10), nullable=False),
    sa.Column('conference', sa.String(length=50), nullable=False),
    sa.Column('logo', sa.String(length=200), nullable=False),
    sa.Column('mascot', sa.String(length=50), nullable=False),
    sa.Column('school', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team')
    op.drop_table('game')
    # ### end Alembic commands ###
