"""empty message

Revision ID: 3910ee0901a9
Revises: 24c24f300919
Create Date: 2022-08-08 02:31:39.667835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3910ee0901a9'
down_revision = '24c24f300919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pick',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.CheckConstraint('created < start_date', name='game_is_in_future'),
    sa.CheckConstraint('game_away_id = team_id OR game_home_id = team_id', name='team_matches'),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pick')
    # ### end Alembic commands ###
