"""empty message

Revision ID: 3a24e3436e04
Revises: 0d06507a4d4f
Create Date: 2022-08-14 04:30:49.640942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a24e3436e04'
down_revision = '0d06507a4d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entry', sa.Column('conference', sa.String(length=80), nullable=True))
    op.add_column('entry', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('entry', 'year')
    op.drop_column('entry', 'conference')
    # ### end Alembic commands ###
