"""empty message

Revision ID: 3fbfe52a35da
Revises: 1ad81b57b222
Create Date: 2022-08-07 03:55:48.078124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fbfe52a35da'
down_revision = '1ad81b57b222'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('away_team', sa.String(length=50), nullable=False))
    op.add_column('game', sa.Column('home_team', sa.String(length=50), nullable=False))
    op.add_column('game', sa.Column('start_time', sa.DateTime(), nullable=False))
    op.add_column('game', sa.Column('conference_game', sa.Boolean(), nullable=False))
    op.add_column('game', sa.Column('neutral_site', sa.Boolean(), nullable=False))
    op.add_column('game', sa.Column('season', sa.Integer(), nullable=False))
    op.add_column('game', sa.Column('week', sa.String(length=50), nullable=False))
    op.add_column('game', sa.Column('season_type', sa.String(length=50), nullable=False))
    op.add_column('game', sa.Column('venue', sa.String(length=100), nullable=False))
    op.add_column('game', sa.Column('away_points', sa.Integer(), nullable=True))
    op.add_column('game', sa.Column('home_points', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('game', 'home_points')
    op.drop_column('game', 'away_points')
    op.drop_column('game', 'venue')
    op.drop_column('game', 'season_type')
    op.drop_column('game', 'week')
    op.drop_column('game', 'season')
    op.drop_column('game', 'neutral_site')
    op.drop_column('game', 'conference_game')
    op.drop_column('game', 'start_time')
    op.drop_column('game', 'home_team')
    op.drop_column('game', 'away_team')
    # ### end Alembic commands ###
