"""empty message

Revision ID: 5823a0b3fedd
Revises: 3fbfe52a35da
Create Date: 2022-08-07 05:01:25.744682

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5823a0b3fedd'
down_revision = '3fbfe52a35da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('start_date', sa.DateTime(), nullable=False))
    op.drop_column('game', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('game', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('game', 'start_date')
    # ### end Alembic commands ###
