"""empty message

Revision ID: ca6d66718c3a
Revises: 235015bb98b4
Create Date: 2022-08-14 03:42:32.369597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca6d66718c3a'
down_revision = '235015bb98b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('entry_creator_id_fkey', 'entry', type_='foreignkey')
    op.create_foreign_key(None, 'entry', 'users', ['creator_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('game_away_id_fkey', 'game', type_='foreignkey')
    op.drop_constraint('game_home_id_fkey', 'game', type_='foreignkey')
    op.create_foreign_key(None, 'game', 'team', ['away_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'game', 'team', ['home_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('pick_entry_id_fkey', 'pick', type_='foreignkey')
    op.drop_constraint('pick_team_id_fkey', 'pick', type_='foreignkey')
    op.drop_constraint('pick_game_id_fkey', 'pick', type_='foreignkey')
    op.create_foreign_key(None, 'pick', 'entry', ['entry_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pick', 'team', ['team_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pick', 'game', ['game_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pick', type_='foreignkey')
    op.drop_constraint(None, 'pick', type_='foreignkey')
    op.drop_constraint(None, 'pick', type_='foreignkey')
    op.create_foreign_key('pick_game_id_fkey', 'pick', 'game', ['game_id'], ['id'])
    op.create_foreign_key('pick_team_id_fkey', 'pick', 'team', ['team_id'], ['id'])
    op.create_foreign_key('pick_entry_id_fkey', 'pick', 'entry', ['entry_id'], ['id'])
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.drop_constraint(None, 'game', type_='foreignkey')
    op.create_foreign_key('game_home_id_fkey', 'game', 'team', ['home_id'], ['id'])
    op.create_foreign_key('game_away_id_fkey', 'game', 'team', ['away_id'], ['id'])
    op.drop_constraint(None, 'entry', type_='foreignkey')
    op.create_foreign_key('entry_creator_id_fkey', 'entry', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###
