"""empty message

Revision ID: ff84f2f9c0e1
Revises: 372edbc9a5c4
Create Date: 2022-08-08 03:39:04.901366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff84f2f9c0e1'
down_revision = '372edbc9a5c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pick', sa.Column('entry_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'pick', 'entry', ['entry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pick', type_='foreignkey')
    op.drop_column('pick', 'entry_id')
    op.drop_table('entry')
    # ### end Alembic commands ###
